language: python
python:
  - "3.5"

env:
  global:
      - DEPLOY_HOST=rpm.palette-software.com
      - DEPLOY_PATH=/var/palette-rpm-repo
      - DEPLOY_USER=palette-rpm

      # travis encrypt DEPLOY_PASS=...
      - secure: "Wv/0G0CeAp75CTd/7rShCr1z9bX6DhQ9ToDDqZVDT+sb7utABK4YF/tOUHOTk6HJyyctMHOIuV2rVmxTHWINHVTgI+ckGfHrIUe/xkY/mRnjngP/VvtEbThQ9BfEdiqE3hSPwJjR5fF3Kl/lG8rNZqLsqZKkID6RP4ELAN/Gmwfbv/gUcDmjzaCfGccX1OZpX7HMrWOf7DaSCouAz7lZW/pJXeBguz+e0oTDwB/uljJdf8cVagfPaGEj3AHid6+zidu2rBPEq7k3eFmHCNnTYSK3cVfPpJuxPVRRGtX3/PueLOUQanBNsl4piIgVvxp0vfr+EB6aaEh72q2CLGZYqXJ9+JnaAAE9UEc4g+vAFQXKf3ohRkj2P2Xa5cvEPoPPi+qWbVfhyQWTEX5JropCwvap+GudP5O5zTU5gNoZ/U8DzT2w6AsrRNoCkYkxw5kmBphuvg48/jM2QRnwl/4s/OZadtzT/gfpvKF87ieXpYcNvcSIBKJnFbzLMNthiOJW+2c7L6YQexd+CiY2RhhKmV3H54BBF+Pel2VqOgj5x1ipZkEAO1H5NpZwI0Qw1Nb1gH4AgU+CEand9N8h8YopKpk+oUdJgIHAJv//onjo8JCzdRKYpxmSKeT3KaQzL3AwPYkTYnWspmIFxnaXPJI2VwlgsLhaSn/0FXjxx9M+Ypk="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

# Put a proper version string into the version file
before_script:
  - export BUILD_TAG="$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d").$TRAVIS_BUILD_NUMBER"
  - echo "==== Setting ${BUILD_TAG} as version ===="

script:
  - export VERSION_NUMBER="$(sed -n 's/Version. \([0-9]*\.[0-9]*\.[0-9]*$\)/\1/p' < gp-import-config.yml)"
  - export VERSION=v$VERSION_NUMBER.$TRAVIS_BUILD_NUMBER

  # Run tests
  - python -m pytest test/

  # Prepare for rpm-build
  - mkdir -p rpm-build
  - pushd rpm-build
  - mkdir -p _build

  # Create directories
  - mkdir -p opt/insight-gp-import
  - mkdir -p var/log/insight-gp-import
  - mkdir -p etc/palette-insight-server

  # Copy the package contents
  - cp -v ../*.py opt/insight-gp-import
  - cp -v ../requirements.txt opt/insight-gp-import
  - cp -v ../*.sh opt/insight-gp-import
  - cp -v ../gp-import-config.yml etc/palette-insight-server

  - echo "BUILDING VERSION:$VERSION"

  # build the rpm
  - rpmbuild -bb --buildroot $(pwd) --define "version $VERSION" --define "buildrelease $TRAVIS_BUILD_NUMBER" --define "_rpmdir $(pwd)/_build" ../insight-gp-import.spec
  - popd

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
